import { config } from "process";
import { LangOptions, LanguageProvider } from "../language-provider";
import { LangContentPart, LangImageInput, LangMessage, LangMessages } from "../messages";
import { OpenAILikeConfig } from "./openai-chat-completions-lang";
import { OpenAIResponsesOptions } from "./openai-responses-lang";
import { BodyPartForOpenAIResponses, prepareBodyPartForOpenAIResponsesAPI } from "./openai-responses-messages";
import { processResponseStream } from "../../process-response-stream.ts";

// We're not going to define all the things that go into responses, there a LOT of them;
// Check the autogenerated types from openai here: @todo link
export class InProgressOpenAIResponse {
  id: string;
  items: OpenAIResponseItem[];
  messages: LangMessages;

  constructor(messages: LangMessages) {
    this.items = [];
    this.messages = messages;
  }

  handleEvent(data: any) {
    if (!('type' in data)) {
      console.warn('Unknown data from server:', data);
      return;
    }
    
    if (!('type' in data)) {
      console.warn('Unknown data from server:', data);
      return;
    }

    switch (data.type) {
      case 'response.created':
        this.id = data.response.id;
        break;
      case 'response.output_item.added':
        this.addItem(data.item);
        break;
      case 'response.output_item.done':
        break;
      case 'response.content_part.added':
        break;
      case 'response.content_part.done':
        break;

      // Deltas that we care about (feel free to add more if you want to show them in-progress somewher)
      case 'response.output_text.delta':
      case 'response.function_call_arguments.delta':
        this.applyDelta(data.item_id, data.delta);
        break;
    }
  }

  addItem(item: OpenAIResponseItem) {
    this.items.push(item);

    if (item.type === 'message') {
      if (item.role === 'assistant') {
        this.messages.addAssistantMessage(item.text ?? '');
        item.targetMessage = this.messages[this.messages.length - 1];
      } else {
        console.warn('Unknown role:', item.role, 'for item:', item);
      }
    }
  }

  getItem(id: string): OpenAIResponseItem | undefined {
    return this.items.find(r => r.id === id);
  }

  applyDelta(itemId: string, delta: string) {
    const item = this.getItem(itemId);
    if (item) {
      item.text += delta;

      if (item.targetMessage) {
        // @TODO: we need to update different deltas correctly
        if (typeof delta === "string") {
          item.targetMessage.content += delta;
        } else {
          console.warn('Unknown delta type:', typeof delta, 'for item:', item);
        }
      }
    }
  }
}

export type OpenAIResponseItem = {
  id: string;
  type: string;
  // We link our messages to items so we can mutate them as items are updated
  targetMessage?: LangMessage; 
  [key: string]: any;
}

export class OpenAIResponsesLangTwo extends LanguageProvider {

  private model: string;
  private apiKey: string;
  private baseURL = "https://api.openai.com/v1";

  constructor(options: OpenAIResponsesOptions) {
    super("OpenAI Responses");

    this.model = options.model;
    this.apiKey = options.apiKey;
  }

  async ask(prompt: string, options?: LangOptions): Promise<LangMessages> {
    const messages = new LangMessages();

    messages.push({ role: "user", content: prompt });

    return this.chat(messages, options);
  }

  async chat(messages: LangMessage[] | LangMessages, options?: LangOptions): Promise<LangMessages> {
    const msgCollection = messages instanceof LangMessages
      ? messages
      : new LangMessages(messages);

    await this.sendToApi(msgCollection, options);

    return msgCollection;
  }

  private async sendToApi(msgCollection: LangMessages, options?: LangOptions): Promise<void> {
    const bodyPart = prepareBodyPartForOpenAIResponsesAPI(msgCollection);
    
    const body = {
      model: this.model,
      ...{ stream: true },
      ...bodyPart,
      // @TODO: have a function that calculates the maxTokens (take a look at other providers for that)
      ...(typeof options?.maxTokens === 'number' ? { max_output_tokens: options.maxTokens } : {}),
    };

    const req = {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Accept": "text/event-stream",
        Authorization: `Bearer ${this.apiKey}`
      },
      body: JSON.stringify(body),
    };

    const inProgressResponses = new InProgressOpenAIResponse(msgCollection);
    const response = await fetch(`${this.baseURL}/responses`, req);
    await processResponseStream(response, (data) => inProgressResponses.handleEvent(data));
  }

}